version: '1'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASS
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    command:
      - --default-time-zone=+00:00
      - --sql-require-primary-key=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
